<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE xsl:stylesheet [
 <!ENTITY nbsp "&#160;" >
 ]>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output doctype-public="-//W3C//DTD XHTML 1.0 Transitional//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `source.xml'  -->
</xsl:output><xsl:template match="/">
		<xsl:element name="html">
			<xsl:text>
</xsl:text>
			<xsl:element name="body">
				<xsl:text>
this</xsl:text>&nbsp;<xsl:text>is</xsl:text>&nbsp;<xsl:text>a</xsl:text>&nbsp;<xsl:text>string</xsl:text>&nbsp;<xsl:text>with</xsl:text>&nbsp;<xsl:text>entities
</xsl:text></xsl:element>
			<xsl:text>
</xsl:text></xsl:element></xsl:template></xsl:stylesheet>