<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `source.xml'  -->
</xsl:output><xsl:template match="/"><xsl:apply-templates select="/*/thing2"/></xsl:template><xsl:template match="thing2"><xsl:element name="zzz"><xsl:attribute name="id"><xsl:text><![CDATA[zzz]]></xsl:text></xsl:attribute><xsl:value-of select="stuff"/></xsl:element></xsl:template></xsl:stylesheet>