<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `source.xml'  -->
</xsl:output><xsl:include href="source.xml-yyy.xsl"/><xsl:template match="/"><xsl:element name="xxx"><xsl:text>
	</xsl:text><xsl:element name="www"><xsl:value-of select="*/cat/stuff"/></xsl:element><xsl:text>
	</xsl:text><xsl:call-template name="source-xml-yyy"/><xsl:text>
</xsl:text></xsl:element></xsl:template></xsl:stylesheet>