<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE xsl:stylesheet>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html"><!--  generated by dexter-0.9-beta (copyright (c) 2007-2011 Michael Dykman, Lauren Enterprises) from `/home/michael/projects/dexter-xsl/docs/examples/test-dx-ghost/source.xml'   --></xsl:output>
<xsl:preserve-space elements="*"></xsl:preserve-space>

<xsl:template match="/">

<tests><xsl:text>
		
			</xsl:text><b>bolded</b><xsl:text>
		
		
			
				</xsl:text><b>bold content</b><xsl:text>
			
		
</xsl:text></tests>

</xsl:template>

</xsl:stylesheet>