<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE xsl:stylesheet>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html"><!--  generated by dexter-0.9-beta (copyright (c) 2007-2011 Michael Dykman, Lauren Enterprises) from `/home/michael/workspace/dexter-xsl/in.xml'   --></xsl:output>
<xsl:preserve-space elements="*"></xsl:preserve-space>

<xsl:template match="/">

<html><xsl:text>
</xsl:text><head><xsl:text>
</xsl:text></head><xsl:text>
</xsl:text><body>THING</body><xsl:text>
</xsl:text></html>
</xsl:template>

</xsl:stylesheet>
