<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:template match="/">
		<xsl:element name="select"><xsl:attribute name="name">pet</xsl:attribute>			<xsl:text>
	</xsl:text>
					<xsl:element name="option">				<xsl:text>choose a pet</xsl:text>
			</xsl:element>

		<xsl:apply-templates mode="aa14cfb76e145f920" select="/result/pets/pet"/>
			<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>
<xsl:template match="/result/pets/pet" mode="aa14cfb76e145f920"><xsl:variable name="DexterDepthLevel1"><xsl:value-of select="position()"/></xsl:variable>				<xsl:element name="option"><xsl:value-of select="."/></xsl:element>

			</xsl:template>
</xsl:stylesheet>