<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman) from `source.xml'  -->
</xsl:output>

<xsl:template match="/">
		<xsl:element name="select"><xsl:attribute name="name">pet</xsl:attribute>			<xsl:text>
	</xsl:text>
					<xsl:element name="option">				<xsl:text>choose a pet</xsl:text>
			</xsl:element>

		<xsl:apply-templates mode="a8885d8fa715a9622" select="/result/pets/pet"/>
			<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>

<xsl:template match="/result/pets/pet" mode="a8885d8fa715a9622">				<xsl:element name="option"><xsl:if test="string-length(.)"><xsl:value-of select="."/></xsl:if></xsl:element>

			</xsl:template>
</xsl:stylesheet>