<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `nested-dx-sub.xml'  -->
</xsl:output><xsl:include href="nested-dx-sub.xml-zzz.xsl"/><xsl:template match="/"><xsl:apply-templates select="*/thing1"/></xsl:template><xsl:template match="thing1"><xsl:element name="yyy"><xsl:attribute name="id"><xsl:text><![CDATA[yyy]]></xsl:text></xsl:attribute>
	<xsl:element name="span"><xsl:value-of select="stuff"/></xsl:element>
		<xsl:apply-templates select="/*/thing2"/>
	</xsl:element></xsl:template></xsl:stylesheet>