<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman) from `source.xml'  -->
</xsl:output>

<xsl:variable name="lookupdata" select="document('lookup.xml')"/><xsl:template match="/">
		<xsl:element name="tests">			<xsl:text>
	</xsl:text>
		<xsl:apply-templates mode="a8ee514fcc6974c53" select="data"/>
			<xsl:text>

</xsl:text>
		</xsl:element>

	</xsl:template>

<xsl:template match="data" mode="a8ee514fcc6974c53">				<xsl:element name="div">					<xsl:text>
		</xsl:text>
									<xsl:element name="span"><xsl:if test="string-length(title)"><xsl:call-template name="lookup"><xsl:with-param name="key"><xsl:value-of select="title"/></xsl:with-param><xsl:with-param name="data" select="$lookupdata"/></xsl:call-template></xsl:if></xsl:element>

									<xsl:text>
		</xsl:text>
									<xsl:element name="span"><xsl:if test="string-length(first)"><xsl:value-of select="first"/></xsl:if></xsl:element>

									<xsl:text>
		</xsl:text>
									<xsl:element name="span"><xsl:if test="string-length(last)"><xsl:value-of select="last"/></xsl:if></xsl:element>

									<xsl:text>
	</xsl:text>
				</xsl:element>

			</xsl:template>

<xsl:template name="lookup">
	<xsl:param name="key"/>
	<xsl:param name="data"/>
	<xsl:value-of select="$data/data/entry[@key=$key]/*|$data/data/entry[@key=$key]/text()"/>
</xsl:template>
</xsl:stylesheet>