<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `../docs/docster.html'  -->
</xsl:output><xsl:template match="/"><xsl:element name="html">
<xsl:element name="head">
<xsl:element name="style"><xsl:attribute name="type">text/css</xsl:attribute>
@import url("style.css");
</xsl:element>

<xsl:element name="title"><xsl:value-of select="*/title"/></xsl:element>

<xsl:element name="meta"><xsl:attribute name="content">Global</xsl:attribute><xsl:attribute name="name">Distribution</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">Michael Dykman &lt;michael@dykman.org&gt;</xsl:attribute><xsl:attribute name="name">Author</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">2007,2008 Michael Dykman</xsl:attribute><xsl:attribute name="name">Copyright</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">General</xsl:attribute><xsl:attribute name="name">Rating</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">XSL,XSLT,XHTML,XML,W3C,DocType,web,development,web-development,tool,code-generation,convert,converter</xsl:attribute><xsl:attribute name="name">Keywords</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">Dexter is a tool for simplifying the production of XSL stylesheets.</xsl:attribute><xsl:attribute name="name">Description</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">dexter-0.1.6-beta (c) 2007,2008 Michael Dykman</xsl:attribute><xsl:attribute name="name">Generator</xsl:attribute></xsl:element><xsl:element name="meta"><xsl:attribute name="content">index, follow</xsl:attribute><xsl:attribute name="name">Robots</xsl:attribute></xsl:element>
</xsl:element>
<xsl:element name="body">
<xsl:element name="div"><xsl:attribute name="class">foo</xsl:attribute><xsl:element name="span"> <xsl:element name="a"><xsl:attribute name="name">TOP</xsl:attribute></xsl:element></xsl:element>
<xsl:element name="div">

<xsl:element name="h1"><xsl:value-of select="*/title"/></xsl:element>

<xsl:if test="*/subtitle"><xsl:element name="h5"><xsl:value-of select="*/subtitle"/></xsl:element></xsl:if>
</xsl:element>

<xsl:element name="div"><xsl:attribute name="style">float: right; width: 35%</xsl:attribute>
<xsl:element name="div"><xsl:attribute name="style">clear: both; align: left; width: 100%;</xsl:attribute>

<xsl:element name="span"><xsl:attribute name="class">author</xsl:attribute><xsl:attribute name="style">width: 100% align : left;</xsl:attribute>author:
 
<xsl:value-of select="*/author"/>
</xsl:element></xsl:element>
<xsl:element name="br"/>

 
 
<xsl:for-each select="*/references/reference"><xsl:element name="div"><xsl:attribute name="style">clear: both;</xsl:attribute>
<xsl:element name="div"><xsl:attribute name="style">padding-left: 5px; left-margin: 5px;</xsl:attribute>
	
<xsl:element name="a"><xsl:attribute name="href"><xsl:value-of select="url"/></xsl:attribute><xsl:value-of select="title"/></xsl:element><xsl:element name="br"/>

<xsl:element name="div"><xsl:attribute name="style">left-margin: 5px;</xsl:attribute><xsl:value-of select="summary"/></xsl:element>
</xsl:element>
</xsl:element></xsl:for-each>







</xsl:element>

<xsl:element name="div"><xsl:attribute name="style">float: left; width: 55%</xsl:attribute>


<xsl:element name="div"><xsl:attribute name="style">float: left; clear: both;</xsl:attribute>
<xsl:element name="h2"><xsl:attribute name="width">100%</xsl:attribute>Overview</xsl:element>
<xsl:element name="p">

<xsl:for-each select="*/overview/para"><xsl:element name="i"><xsl:value-of select="."/></xsl:element></xsl:for-each>

</xsl:element>
</xsl:element>



<xsl:if test="count(*/section) &gt; 1"><xsl:element name="div"><xsl:attribute name="style">top-margin: 15px;</xsl:attribute>
<xsl:element name="h2">Table of Contents</xsl:element>
<xsl:element name="a"><xsl:attribute name="name">TOC</xsl:attribute></xsl:element>

<xsl:element name="div"><xsl:attribute name="style">left-margin: 30px;</xsl:attribute><xsl:for-each select="*/section"><xsl:element name="a"><xsl:attribute name="href"><xsl:choose><xsl:when test="title/text()"><xsl:text><![CDATA[#]]></xsl:text><xsl:value-of select="title"/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:attribute><xsl:value-of select="title"/></xsl:element><xsl:element name="br"/>
	
</xsl:for-each></xsl:element>
</xsl:element></xsl:if>


</xsl:element>

</xsl:element>

<xsl:element name="div"><xsl:attribute name="style">clear: both</xsl:attribute>

<xsl:for-each select="*/section"><xsl:element name="div"><xsl:element name="a"><xsl:attribute name="name"><xsl:choose><xsl:when test="title/text()"><xsl:text/><xsl:value-of select="title"/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:attribute></xsl:element>

<xsl:element name="h2"><xsl:attribute name="width">80%</xsl:attribute><xsl:value-of select="title"/></xsl:element>


<xsl:if test="overview"><xsl:element name="div"><xsl:attribute name="width">60%</xsl:attribute><xsl:for-each select="overview/para">
<xsl:element name="p"><xsl:element name="i"><xsl:value-of select="."/></xsl:element></xsl:element>

</xsl:for-each></xsl:element></xsl:if>


<xsl:element name="div"><xsl:attribute name="class">listing</xsl:attribute><xsl:for-each select="chapter"><xsl:element name="a"><xsl:attribute name="href"><xsl:choose><xsl:when test="../title/text() and title/text()"><xsl:text><![CDATA[#]]></xsl:text><xsl:value-of select="../title"/><xsl:text><![CDATA[-]]></xsl:text><xsl:value-of select="title"/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:attribute>&gt; <xsl:value-of select="title"/></xsl:element><xsl:element name="br"/>
</xsl:for-each></xsl:element>
<xsl:element name="a"><xsl:attribute name="href">#TOC</xsl:attribute>&lt;&lt; Table of Contents</xsl:element><xsl:element name="br"/>
<xsl:element name="a"><xsl:attribute name="href">#TOP</xsl:attribute>&lt;&lt; Top</xsl:element><xsl:element name="br"/>


<xsl:for-each select="chapter"><xsl:element name="div"><xsl:attribute name="class">section</xsl:attribute>

<xsl:element name="a"><xsl:attribute name="name"><xsl:choose><xsl:when test="../title/text() and title/text()"><xsl:text/><xsl:value-of select="../title"/><xsl:text><![CDATA[-]]></xsl:text><xsl:value-of select="title"/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:attribute></xsl:element>
<xsl:element name="h3"><xsl:value-of select="title"/></xsl:element>


<xsl:element name="div"><xsl:for-each select="*">

<xsl:choose><xsl:when test="local-name(.) = &quot;para&quot;"><xsl:element name="p"><xsl:for-each select="link|./text()">

<xsl:choose><xsl:when test="./self::text()"><xsl:value-of select="."/></xsl:when><xsl:when test="local-name(.) = &quot;link&quot;"><xsl:element name="a"><xsl:attribute name="href"><xsl:value-of select="@url"/></xsl:attribute><xsl:value-of select="."/></xsl:element></xsl:when></xsl:choose></xsl:for-each></xsl:element></xsl:when><xsl:when test="local-name(.) = &quot;code&quot;"><xsl:element name="div"><xsl:element name="pre"><xsl:attribute name="style">width: 80%;</xsl:attribute><xsl:value-of select="."/></xsl:element>
</xsl:element></xsl:when></xsl:choose></xsl:for-each></xsl:element>


<xsl:element name="div"><xsl:attribute name="style">text-align: center</xsl:attribute><xsl:element name="a"><xsl:attribute name="href"><xsl:choose><xsl:when test="../title/text()"><xsl:text><![CDATA[#]]></xsl:text><xsl:value-of select="../title"/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:attribute><xsl:value-of select="../title"/></xsl:element> -- <xsl:if test="count(*/section) &gt; 1"><xsl:element name="span"><xsl:element name="a"><xsl:attribute name="href">#TOC</xsl:attribute>Table
of Contents</xsl:element>-- </xsl:element></xsl:if><xsl:element name="a"><xsl:attribute name="href">#TOP</xsl:attribute>Top</xsl:element></xsl:element>
<xsl:element name="br"/>
<xsl:element name="br"/>
</xsl:element></xsl:for-each>
<xsl:element name="br"/>
</xsl:element></xsl:for-each>
<xsl:element name="div"><xsl:attribute name="class">copy</xsl:attribute><xsl:element name="sub"><xsl:value-of select="*/copyright"/></xsl:element>
</xsl:element>
</xsl:element>
</xsl:element>
</xsl:element></xsl:template></xsl:stylesheet>