<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output encoding="UTF-8" indent="yes" media-type="text/html" method="html">
<!-- generated by dexter                                      -->
<!-- dexter (c) 2007,2008 Michael Dykman <michael@dykman.org> -->
<!-- Free for use under version 2.0 of the Artistic License.  -->
<!-- http://www.opensource.org/licences/artistic-license.php  -->
</xsl:output>
<xsl:template match="/"> = <xsl:value-of disable-output-escaping="yes" select="normalize-space(*/title)"></xsl:value-of> =

  <xsl:if test="*/subtitle">=== <xsl:value-of disable-output-escaping="yes" select="normalize-space(*/subtitle)"></xsl:value-of> ===</xsl:if>

==== author: <xsl:value-of disable-output-escaping="yes" select="normalize-space(*/author)"></xsl:value-of> ====

<xsl:for-each select="*/section">
 
 == <xsl:value-of disable-output-escaping="yes" select="normalize-space(title)"></xsl:value-of> ==
  
  <xsl:for-each select="overview/para"> _ <xsl:value-of disable-output-escaping="yes" select="normalize-space(.)"></xsl:value-of> _ 
  </xsl:for-each>
  
<xsl:for-each select="chapter">
  
  === <xsl:value-of disable-output-escaping="yes" select="normalize-space(title)"></xsl:value-of> ===
  
  <xsl:for-each select="*">
   
<xsl:choose>
<xsl:when test="local-name(.)=&quot;para&quot;">
<xsl:for-each select="link|./text()">
   
    
<xsl:choose>
<xsl:when test="./self::text()">
<xsl:value-of disable-output-escaping="yes" select="normalize-space(.)"></xsl:value-of>
</xsl:when>
<xsl:when test="local-name(.)=&quot;link&quot;"> [ <xsl:value-of disable-output-escaping="yes" select="."></xsl:value-of> ] </xsl:when>
</xsl:choose>
   
</xsl:for-each>
</xsl:when>
<xsl:when test="local-name(.)=&quot;code&quot;">

    {{{ <xsl:value-of disable-output-escaping="yes" select="."></xsl:value-of> }}}

    </xsl:when>
</xsl:choose>
</xsl:for-each>
 
</xsl:for-each>

</xsl:for-each>

    ,, <xsl:value-of disable-output-escaping="yes" select="normalize-space(*/copyright)"></xsl:value-of> ,,
  
</xsl:template>
</xsl:stylesheet>
