<!DOCTYPE xsl:stylesheet>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html"><!--  generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman, Lauren Enterprises) from `source.xml'   --></xsl:output>
<xsl:preserve-space elements="*"></xsl:preserve-space>

<xsl:template match="/">

<tests><xsl:text>
		</xsl:text><xsl:apply-templates mode="md-eb9bc444c9e710cd" select="data/things/thing"></xsl:apply-templates>
<xsl:text>
</xsl:text></tests>

</xsl:template>

<xsl:template match="thing" mode="md-eb9bc444c9e710cd" name="md-eb9bc444c9e710cd">
<xsl:variable name="myvar" select="."></xsl:variable><xsl:variable name="myvarindex" select="position()"></xsl:variable><div><xsl:attribute name="id"><xsl:text>myvar</xsl:text><xsl:if test="last() > 1">-<xsl:value-of select="generate-id()"></xsl:value-of></xsl:if></xsl:attribute><xsl:if test="string-length($myvar/name)"><xsl:value-of select="$myvar/name"></xsl:value-of></xsl:if></div>
</xsl:template>

</xsl:stylesheet>