<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:import href="source.xml-yyy.xsl"/>
<xsl:template match="/">
		<xsl:element name="xxx">			<xsl:text>
	</xsl:text>
					<xsl:element name="www"><xsl:value-of select="*/cat/stuff"/></xsl:element>

					<xsl:text>
	</xsl:text>
		<xsl:choose><xsl:when test="*/thing1"><xsl:apply-templates mode="source-xml-yyy" select="*/thing1"/></xsl:when><xsl:otherwise><xsl:call-template name="source-xml-yyy"/></xsl:otherwise></xsl:choose>			<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>
</xsl:stylesheet>