<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman) from `source.xml'  -->
</xsl:output>

<xsl:template match="/">
		<xsl:element name="tests">			<xsl:text>
	</xsl:text>
		<xsl:apply-templates mode="a98bd1755387ea91b" select="data/record"/>
			<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>

<xsl:template match="data/record" mode="a98bd1755387ea91b">				<xsl:element name="div"><xsl:attribute name="id"><xsl:text>group-2</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>					<xsl:text>
			a record
		</xsl:text>
				<xsl:apply-templates mode="af1cca5f5165582dd" select="*"/>
					<xsl:text>

	
		</xsl:text>
									<xsl:element name="div">						<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:if test="string-length(one)"><xsl:value-of select="one"/></xsl:if></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:if test="string-length(two)"><xsl:value-of select="two"/></xsl:if></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:if test="string-length(three)"><xsl:value-of select="three"/></xsl:if></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:if test="string-length(four)"><xsl:value-of select="four"/></xsl:if></xsl:element>

											<xsl:text>
		</xsl:text>
					</xsl:element>

									<xsl:text>
	</xsl:text>
				</xsl:element>

			</xsl:template>

<xsl:template match="*" mode="af1cca5f5165582dd">						<xsl:element name="div"><xsl:if test="string-length(local-name()) and string-length(.)"><xsl:text>new record </xsl:text><xsl:value-of select="local-name()"/><xsl:text> = </xsl:text><xsl:value-of select="."/></xsl:if></xsl:element>

					</xsl:template>
</xsl:stylesheet>