<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:template match="/">
		<xsl:element name="tests">			<xsl:text>
	</xsl:text>
		<xsl:apply-templates mode="ad050c4a6e1585ecd" select="data/record"/>
			<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>
<xsl:template match="data/record" mode="ad050c4a6e1585ecd">				<xsl:element name="div"><xsl:attribute name="id"><xsl:text>group-2</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>					<xsl:text>
			a record
		</xsl:text>
				<xsl:apply-templates mode="ad232aa317fae273b" select="*"/>
					<xsl:text>

	
		</xsl:text>
									<xsl:element name="div">						<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:value-of select="one"/></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:value-of select="two"/></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:value-of select="three"/></xsl:element>

											<xsl:text>
			</xsl:text>
											<xsl:element name="span"><xsl:value-of select="four"/></xsl:element>

											<xsl:text>
		</xsl:text>
					</xsl:element>

									<xsl:text>
	</xsl:text>
				</xsl:element>

			</xsl:template>
<xsl:template match="*" mode="ad232aa317fae273b">						<xsl:element name="div"><xsl:choose><xsl:when test="local-name() and ."><xsl:text>new record </xsl:text><xsl:value-of select="local-name()"/><xsl:text> = </xsl:text><xsl:value-of select="."/></xsl:when><xsl:otherwise><xsl:text/></xsl:otherwise></xsl:choose></xsl:element>

					</xsl:template>
</xsl:stylesheet>