<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:template match="/">
<xsl:apply-templates mode="adba7a64e5501c845" select="data/found"/>
</xsl:template>
<xsl:template match="data/found" mode="adba7a64e5501c845">			<xsl:element name="tests">				<xsl:text>
		</xsl:text>
			<xsl:choose><xsl:when test="@value = 'y'">						<xsl:element name="div"><xsl:attribute name="cond">true</xsl:attribute><xsl:attribute name="id"><xsl:text>test-1a</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>							<xsl:text>only one should show with 42</xsl:text>
						</xsl:element>

					</xsl:when><xsl:otherwise>						<xsl:element name="div"><xsl:attribute name="cond">false</xsl:attribute><xsl:attribute name="id"><xsl:text>test-1b</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>							<xsl:text>only one should show with 42</xsl:text>
						</xsl:element>

					</xsl:otherwise></xsl:choose>				<xsl:text>
		</xsl:text>
			<xsl:choose><xsl:when test="@value = 'n'">						<xsl:element name="div"><xsl:attribute name="cond">false</xsl:attribute><xsl:attribute name="id"><xsl:text>test-2a</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>							<xsl:text>only one should show with 43</xsl:text>
						</xsl:element>

					</xsl:when><xsl:otherwise>						<xsl:element name="div"><xsl:attribute name="cond">true</xsl:attribute><xsl:attribute name="id"><xsl:text>test-2b</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>							<xsl:text>only one should show with 43</xsl:text>
						</xsl:element>

					</xsl:otherwise></xsl:choose>				<xsl:text>

</xsl:text>
			</xsl:element>

		</xsl:template>
</xsl:stylesheet>