<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman) from `source.xml'  -->
</xsl:output>

<xsl:template name="section">
	<xsl:param name="param1" /> 
	<xsl:call-template name="csv">
		<xsl:with-param name="param1" select="$param1" /> 
		<xsl:with-param name="param2" > :: </xsl:with-param>
	</xsl:call-template>
</xsl:template>

</xsl:stylesheet>
