<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `source.xml'  -->
</xsl:output><xsl:template match="/"><xsl:element name="select"><xsl:attribute name="name">pet</xsl:attribute>
	<xsl:element name="option">choose a pet</xsl:element><xsl:for-each select="result/pets/pet"><xsl:element name="option"><xsl:value-of select="."/></xsl:element></xsl:for-each>
</xsl:element></xsl:template></xsl:stylesheet>