<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:import href="source.xml-zzz.xsl"/>
<xsl:template match="/"><xsl:choose><xsl:when test="*/thing1"><xsl:apply-templates mode="source-xml-yyy" select="*/thing1"/></xsl:when><xsl:otherwise><xsl:call-template name="source-xml-yyy"/></xsl:otherwise></xsl:choose></xsl:template>
<xsl:template match="*/thing1" mode="source-xml-yyy" name="source-xml-yyy">
					<xsl:element name="yyy"><xsl:attribute name="id"><xsl:text>yyy</xsl:text><xsl:if test="last() &gt; 1">-<xsl:value-of select="generate-id()"/></xsl:if></xsl:attribute>						<xsl:text>
		</xsl:text>
					<xsl:value-of select="stuff"/>						<xsl:text>
		</xsl:text>
					<xsl:choose><xsl:when test="/*/thing2"><xsl:apply-templates mode="source-xml-zzz" select="/*/thing2"/></xsl:when><xsl:otherwise><xsl:call-template name="source-xml-zzz"/></xsl:otherwise></xsl:choose>						<xsl:text>
	</xsl:text>
					</xsl:element>

				</xsl:template>
</xsl:stylesheet>