<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.9-beta (copyright (c) 2007-2010 Michael Dykman) from `source.xml'  -->
</xsl:output>

<xsl:template match="/">
		<xsl:element name="html">			<xsl:text>
	</xsl:text>
					<xsl:element name="body">				<xsl:text>
		</xsl:text>
			<xsl:apply-templates mode="a4c59afa068da0892" select="data/customers"/>
				<xsl:text>
		</xsl:text>
			<xsl:apply-templates mode="a826b53a74fe62261" select="data/staff"/>
				<xsl:text>
	</xsl:text>
			</xsl:element>

					<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>

<xsl:template match="data/customers" mode="a4c59afa068da0892">					<xsl:element name="div">						<xsl:text>
			</xsl:text>
					<xsl:call-template name="persons"/>						<xsl:text>
		</xsl:text>
					</xsl:element>

				</xsl:template>

<xsl:template name="persons"><xsl:apply-templates mode="ab397445cab6e67c6" select="person"/>
</xsl:template>

<xsl:template match="person" mode="ab397445cab6e67c6">								<xsl:element name="div">									<xsl:text>
				</xsl:text>
																	<xsl:element name="div"><xsl:if test="string-length(first)"><xsl:value-of select="first"/></xsl:if></xsl:element>

																	<xsl:text>,
				</xsl:text>
																	<xsl:element name="div"><xsl:if test="string-length(last)"><xsl:value-of select="last"/></xsl:if></xsl:element>

																	<xsl:text>
			</xsl:text>
								</xsl:element>

							</xsl:template>

<xsl:template match="data/staff" mode="a826b53a74fe62261">					<xsl:element name="div">						<xsl:text>
			</xsl:text>
					<xsl:call-template name="persons"/>						<xsl:text>
		</xsl:text>
					</xsl:element>

				</xsl:template>
</xsl:stylesheet>