<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `source.xml'  -->
</xsl:output>
<xsl:template match="/">
		<xsl:element name="html">			<xsl:text>
	</xsl:text>
					<xsl:element name="body">				<xsl:text>
		</xsl:text>
			<xsl:apply-templates mode="ab15bb47800e6b123" select="data/customers"/>
				<xsl:text>
		</xsl:text>
			<xsl:apply-templates mode="a35b88fcb7a294ebc" select="data/staff"/>
				<xsl:text>
	</xsl:text>
			</xsl:element>

					<xsl:text>
</xsl:text>
		</xsl:element>

	</xsl:template>
<xsl:template match="data/customers" mode="ab15bb47800e6b123">					<xsl:element name="div">						<xsl:text>
			</xsl:text>
					<xsl:call-template name="persons"/>						<xsl:text>
		</xsl:text>
					</xsl:element>

				</xsl:template>
<xsl:template name="persons"><xsl:apply-templates mode="a58c043a4e949a7d1" select="person"/>
</xsl:template>
<xsl:template match="person" mode="a58c043a4e949a7d1">								<xsl:element name="div">									<xsl:text>
				</xsl:text>
																	<xsl:element name="div"><xsl:value-of select="first"/></xsl:element>

																	<xsl:text>,
				</xsl:text>
																	<xsl:element name="div"><xsl:value-of select="last"/></xsl:element>

																	<xsl:text>
			</xsl:text>
								</xsl:element>

							</xsl:template>
<xsl:template match="data/staff" mode="a35b88fcb7a294ebc">					<xsl:element name="div">						<xsl:text>
			</xsl:text>
					<xsl:call-template name="persons"/>						<xsl:text>
		</xsl:text>
					</xsl:element>

				</xsl:template>
</xsl:stylesheet>