<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter from `source.xml'  -->
</xsl:output><xsl:include href="source.xml-zzz.xsl"/><xsl:template match="/"><xsl:call-template name="source-xml-yyy"/></xsl:template><xsl:template name="source-xml-yyy"><xsl:element name="yyy"><xsl:attribute name="id"><xsl:text>yyy</xsl:text></xsl:attribute><xsl:text>
		</xsl:text><xsl:value-of select="*/thing1/stuff"/><xsl:text>
		</xsl:text><xsl:call-template name="source-xml-zzz"/><xsl:text>
	</xsl:text></xsl:element></xsl:template></xsl:stylesheet>