<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" encoding="UTF-8"
		indent="no" media-type="text/html" method="html">
		<!-- generated by dexter from `../resources/profile.html'  -->
	</xsl:output>
	<xsl:template match="/">
		<xsl:element name="html">
			<xsl:element name="head">

				<xsl:element name="title">
					profile of
					<xsl:value-of select="*/profile/first" />
					<xsl:value-of select="*/profile/last" />
				</xsl:element>
			</xsl:element>
			<xsl:element name="body">
				<xsl:choose>
					<xsl:when test="*/error">
						<xsl:element name="div">
							<xsl:element name="b">
								<xsl:value-of select="*/error" />
							</xsl:element>
						</xsl:element>
					</xsl:when>
					<xsl:otherwise>
						<xsl:element name="table">
							<xsl:attribute name="border">1</xsl:attribute>
							<xsl:element name="tr">
								<xsl:element name="td">
									<xsl:attribute name="rowspan">2</xsl:attribute>
									<xsl:element name="img">
										<xsl:attribute name="src"><xsl:choose><xsl:when test="*/profile/image/text()"><xsl:value-of select="*/profile/image" /></xsl:when><xsl:otherwise><xsl:text><![CDATA[images/no-image.jpg]]></xsl:text></xsl:otherwise></xsl:choose></xsl:attribute>
									</xsl:element>
								</xsl:element>
								<xsl:element name="td">
									<xsl:value-of select="*/profile/username" />
								</xsl:element>
								<xsl:element name="td">
									<xsl:element name="a">
										<xsl:attribute name="href"><xsl:choose><xsl:when test="*/profile/email/text()"><xsl:text><![CDATA[mailto://]]></xsl:text><xsl:value-of select="*/profile/email" /></xsl:when><xsl:otherwise><xsl:text><![CDATA[javascript:alert('no address given');]]></xsl:text></xsl:otherwise></xsl:choose></xsl:attribute>
										email
										<xsl:value-of select="*/profile/first" />
									</xsl:element>
								</xsl:element>
							</xsl:element>
							<xsl:element name="tr">
								<xsl:element name="td">
									<xsl:value-of select="*/profile/first" />
								</xsl:element>
								<xsl:element name="td">
									<xsl:value-of select="*/profile/last" />
								</xsl:element>
							</xsl:element>
						</xsl:element>
					</xsl:otherwise>
				</xsl:choose>


			</xsl:element>
		</xsl:element>
	</xsl:template>
</xsl:stylesheet>